import Image from "next/image";
import { UserButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { getProfileByEmail } from "../../lib/profile";
import { Plan, Profile } from "@/lib/types";
import CoursePlanClient from "./CoursePlanClient";

export default async function CoursePlanPage({
  searchParams,
}: {
  searchParams: Promise<{ planId?: string }>;
}) {
  const { planId } = await searchParams;
  const user = await currentUser();
  const email: string = user?.primaryEmailAddress?.emailAddress;

  if (!email) redirect("/sign-in");

  const profile: Profile = await getProfileByEmail(email);
  const plans: Plan[] = profile?.plans ?? [];

  const plan = plans.find((p) => p.id === planId) ?? plans[plans.length - 1];

  if (!plan) redirect("/profile");
  if (!plan.schedule) redirect("/profile");

  const infoPills = [
    plan.university,
    plan.schedule.course_title,
    "Specialization: " + plan.schedule.specialisation,
    "Major: " + plan.schedule.major,
    "Minor: " + plan.schedule.minor,
    plan.semesterOffering,
    `${plan.yearStart}-${plan.yearEnd}`,
  ].filter(Boolean) as string[];

  return (
    <main className="min-h-screen bg-[#f5f5f2] text-black">
      <header className="border-b border-black/10 bg-[#f5f5f2]">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 md:px-8">
          <div className="flex items-center gap-4">
            <div className="relative h-8 w-8 overflow-hidden rounded-lg">
              <Image
                src="/U-NIT ME-3.png"
                alt="U-NIT ME logo"
                fill
                sizes="32px"
                className="object-contain"
                priority
              />
            </div>
            <span className="text-sm font-medium tracking-tight">U-NIT ME</span>
          </div>
          <UserButton />
        </div>
      </header>

      <CoursePlanClient plan={plan} email={email} infoPills={infoPills} />

      <footer className="border-t border-black/10 px-6 py-5 md:px-8">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
          <p className="text-xs text-black/25">
            Generated by U-NIT ME — always verify with your university&apos;s
            official handbook
          </p>
          <p className="text-xs text-black/20">
            {plan.semesterOffering} • {plan.yearStart}–{plan.yearEnd}
          </p>
        </div>
      </footer>
    </main>
  );
}
