import Image from "next/image";
import { UserButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { Plan, Profile } from "@/lib/types";
import CoursePlanClient from "../CoursePlanClient";
import CoursePlanner from "@/components/CoursePlanner";
import { getProfileByEmail, updateProfile } from "@/lib/profile";
import { deletePendingPlan, getPendingPlan } from "@/lib/pendingPlan";

export default async function CoursePlanPage({
  params,
  searchParams,
}: {
  params: Promise<{ planId: string }>;
  searchParams: Promise<{ pending?: string }>;
}) {
  const { planId } = await params;
  const { pending } = await searchParams;

  console.log("pending:", pending);

  const user = await currentUser();
  const email: string = user?.primaryEmailAddress?.emailAddress;

  if (!email) redirect("/sign-in");

  let plan: Plan | null = null;

  if (pending === "true") {
    // Load from pendingPlan
    plan = await getPendingPlan(email);
  } else {
    // Load from saved plans
    const profile = await getProfileByEmail(email);
    plan = profile?.plans?.find((p) => p.id === planId) ?? null;
  }

  console.log("plan:", plan.schedule);

  if (!plan || !plan.schedule) redirect("/profile");

  async function handleSave() {
    "use server";

    const savedPlan: Plan = {
      ...plan,
      id: crypto.randomUUID(), // fresh ID
      saved: true,
    };
    const profile = await getProfileByEmail(email);
    const existingPlans = profile?.plans ?? [];

    await updateProfile(email, { plans: [...existingPlans, savedPlan] });
    await deletePendingPlan(email);

    redirect(`/course-plan/${savedPlan.id}`);
  }

  async function handleDiscard() {
    "use server";
    await deletePendingPlan(email);
    redirect("/profile");
  }

  const isPending = pending === "true";

  const coursePlanName = plan.planName;

  const infoPills = [
    plan.university,
    plan.schedule.course_title,
    plan.schedule.specialisation && `Specialisation: ${plan.schedule.specialisation}`,
    plan.schedule.major && `Major: ${plan.schedule.major}`,
    plan.schedule.minor && `Minor: ${plan.schedule.minor}`,
    plan.semesterOffering,
    `${plan.yearStart}-${plan.yearEnd}`,
  ].filter(Boolean) as string[];

  return (
    <main className="min-h-screen bg-[#f5f5f2] text-black">
      <header className="border-b border-black/10 bg-[#f5f5f2]">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 md:px-8">
          <div className="flex items-center gap-4">
            <div className="relative h-8 w-8 overflow-hidden rounded-lg">
              <Image
                src="/U-NIT ME-3.png"
                alt="U-NIT ME logo"
                fill
                sizes="32px"
                className="object-contain"
                priority
              />
            </div>
            <span className="text-sm font-medium tracking-tight">U-NIT ME</span>
          </div>
          <UserButton />
        </div>
      </header>

      <CoursePlanClient plan={plan} email={email} infoPills={infoPills} />

      <footer className="border-t border-black/10 px-6 py-5 md:px-8">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
          <p className="text-xs text-black/25">
            Generated by U-NIT ME — always verify with your university&apos;s
            official handbook
          </p>
          <p className="text-xs text-black/20">
            {plan.semesterOffering} • {plan.yearStart}–{plan.yearEnd}
          </p>
        </div>
      </footer>
    </main>
  );
}
